services:
  back:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: myapp_api_prod
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    ports:
      - "80:3000"
    tty: true
    stdin_open: true
    env_file:
      - .env
    environment:
      - RAILS_ENV=production

  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: myapp_sidekiq_prod
    command: bundle exec sidekiq
    env_file:
      - .env
    environment:
      - RAILS_ENV=production
